name: CI/CD Flow

on:
  push:
    # branches: [staging]

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    permissions:
      id-token: write
      contents: read
    env:
      REACT_APP_GRAPHQL_URL: ${{ secrets.REACT_APP_GRAPHQL_URL }}
      CI: false

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: lint
        run: yarn lint

      - name: Generate Schema
        run: yarn schema:gen:ci

      # - name: Cypress run test
      #   uses: cypress-io/github-action@v4
      #   with:
      #     start: yarn start
      #     wait-on: http://localhost:3000
      #     wait-on-timeout: 300
      #     spec: cypress/e2e/**/*.cy.ts

      - name: Build
        if: contains('
          refs/heads/develop
          refs/heads/staging
          refs/heads/main', github.ref)
        run: yarn build

      - name: Cache build artifacts
        if: contains('
          refs/heads/develop
          refs/heads/staging
          refs/heads/main', github.ref)
        uses: actions/cache@v3
        with:
          path: "build/"
          key: build-artifacts-${{ github.sha }}

  deploy:
    name: Deploy App
    runs-on: [self-hosted, linux, x64]
    needs: build
    if: contains('
      refs/heads/develop
      refs/heads/staging
      refs/heads/main', github.ref)

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore build artifacts
        uses: actions/cache@v3
        with:
          path: "build/"
          key: build-artifacts-${{ github.sha }}
